// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koucmhomqeqfmtmibblw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvdWNtaG9tcWVxZm10bWliYmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMTEyNjYsImV4cCI6MjA4Njg4NzI2Nn0.Dle3Vkrw9Pv3NuDrqUTB6qIBU5YKQNFXZ7EY56Q-xtw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});